platform :ios, '7.0'
pod 'ZulaLibrary', :path => "/Users/solomon/Projects/ZulaMobile/src/ios/ZulaLibrary/ZulaLibrary.podspec"
pod 'RoboReader', :path => "/Users/solomon/Projects/OpenSource/RoboReader"
pod 'LLACircularProgressView'
pod 'AFNetworking', '~> 1.3.2'
pod 'CocoaLumberjack'
pod 'SVProgressHUD'
pod 'MWPhotoBrowser', :git => 'https://github.com/yakubbaev/MWPhotoBrowser.git'
pod 'SDSegmentedControl'
pod 'MSPullToRefreshController', :git => 'https://github.com/laplacesdemon/MSPullToRefreshController.git'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'SDWebImage-ProgressView', '~> 0.3.0'
pod 'SWRevealViewController'
#pod 'SSToolkit', '~> 1.0.4'
